[project]
title = "📈 Bullish Brief — Financial Sentiment App"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[colors]
primary = "#0070f3"
secondary = "#7928ca"
background = "#f9f9f9"
text = "#333333"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.my_dataset]
type = "csv"
path = "data/data.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"